- .goreleaser.yml
In order to work, this method requires the environment variable `HOMEBREW_GITHUB_API_TOKEN` to be set.  Since this repository is now public, the default method is sufficient.
> Remove private repository release method

- api/task_status.go
Adding the new set of statuses to the API package so clients will be able to parse them.
> Add extended set of task statuses

- .goreleaser.yml
- Makefile
This change updates the version of GoReleaser we use, and changes the agent used for published commits to `beakerbot`, our automation robot.
> Update goreleaser with beakerbot info

- api/task.go
I'm open to the idea of making this part of the `PATCH` API on tasks, but I decided to make this separate since that `PATCH` API is something users would use to modify metadata on a task, and this is a more specific kind of modification that should really only be performed by things that are part of the system.
ExitCode is a pointer instead of an int literal because the zero value of an int is `0`, and that's also a valid exit code. This way, `nil` means `not provided`.
> Add TaskStatusSpec to API types

- client/client.go
- client/task.go
Updating the API helper for `SetStatus` so sidecars can send statuses with exit codes & messages
> Update SetStatus API helper to v3

- client/client.go
- client/file.go
This fixes the issue where clients targeting old domains won't authenticate after redirect.
The root cause is that Golang strips auth headers (`Cookie`, `Authorization`) after redirect, so we must explicitly copy them.  This change also has a nice side-effect of copying the referrer header, so we'll have logs when requests originate from old domains.
> Copy request headers on redirect

- api/dataset.go
- client/client.go
- client/dataset.go
- client/file.go
- client/iterator.go
- go.mod
- go.sum
- Remove `FileHandle.PresignLink`
- Deprecate `DatasetHandle.Manifest`
- Add `DatasetHandle.Files` (replaces `DatasetHandle.Manifest`)
- Update `FileHandle` functions to communicate directly with FileHeap when possible.
> Communicate directly with FileHeap

- api/task_status.go
Removes statuses already removed from beaker-service and adds a new status that will be used by the service and sidecars in short order.
> Remove deprecated statuses from API package

- README.md
- client/image.go
- cmd/beaker/blueprint/create.go
- cmd/beaker/blueprint/inspect.go
- cmd/beaker/blueprint/pull.go
- cmd/beaker/blueprint/rename.go
- cmd/beaker/blueprint/root.go
- cmd/beaker/experiment/run.go
- cmd/beaker/experiment/spec.go
- cmd/beaker/image/create.go
- cmd/beaker/image/inspect.go
- cmd/beaker/image/pull.go
- cmd/beaker/image/rename.go
- cmd/beaker/image/root.go
- cmd/beaker/main.go
- docs/blueprints.md
- docs/datasets.md
- docs/images.md
- docs/multistage-experiments.md
- docs/parallel-wordcount.yml
This makes a `beaker image` command for every `beaker blueprint` command, and a `--image` flag for every `--blueprint` flag.  Existing `--image` flags (for docker images) continue to work, and a deprecation warning is printed for any commands we plan to remove soon.
> Alias blueprint commands with image commands

- cmd/beaker/dataset/ls.go
- cmd/beaker/dataset/root.go
- cmd/beaker/experiment/run.go
Help text:
```
$ beaker dataset ls -h
usage: beaker dataset ls [<flags>] <dataset> [<prefix>]
List files in a dataset.
Flags:
-h, --help           Show context-sensitive help (also try --help-long and --help-man).
-v, --version        Show application version.
--debug          Print verbose stack traces on error.
--addr="beaker.dev.allenai.org"  
Address of the Beaker service.
--format=FORMAT  Output format
Args:
<dataset>   Dataset name or ID
[<prefix>]  Path prefix
```
Output is human readable by default:
```
$ beaker dataset ls ds_gkjpvk00jvsp files/fff
10KiB  2019-03-19T23:34:30Z  files/fff1adc407242adb4097
100KiB  2019-03-19T23:34:30Z  files/fff3a28889f47261bb12
10KiB  2019-03-19T23:34:30Z  files/fff71ba7055bd435c1fe
10KiB  2019-03-19T23:34:30Z  files/fffe044027d3605abd09
Total: 4 …
```
> Add beaker dataset ls

- client/image.go
When we were copying "blueprint" functions to "image" functions, looks like we forgot one. This PR adds back the missing "SearchImages" based on the "SearchBlueprint" implementation here: https://github.com/allenai/beaker/commit/ecc350d42706e253e26273e58c0dde7e52208386#diff-d89721205eb675cf8ae886fe0e8aad83L155
The endpoint on the Service API side is still there.
> Add back the missing SearchImages function

- client/experiment.go
- cmd/beaker/experiment/create.go
This exposes the "force" query arg that exists on the service's experiment creation API.
> allow uncommitted datasets

- client/client.go
Ref: https://app.asana.com/0/366914398596019/883056111803235/f
When there is a single trailing slash, the field `u.Path` is set to "/". I changed the error behaviour so that if `u.Path` is set this way, then despite it being non-empty the client doesn't break.
> Tweak to permit trailing slash in address for configure command

- go.mod
- go.sum
The new client ensures ...version is a var and not a const to allow linker-time replacement.
> Fixing client version replacement

- cmd/beaker/config/workspace.go
- cmd/beaker/dataset/create.go
- cmd/beaker/experiment/create.go
- cmd/beaker/group/create.go
- cmd/beaker/image/create.go
- config/workspace.go
The leaderboard requires users use the Beaker CLI to create images for the experiments they're going to run. Any change to the CLI or APIs requiring that a workspace be specified will introduce a new step to these leaderboard submissions that will likely be confusing to users who otherwise don't interact with Beaker.
I see two big pluses here:
1. This version of the CLI makes it impossible to create anything in Beaker without specifying a workspace.
2. Leaderboard users can keep using the tool the way they do today and don't need to be any wiser about Beaker's changes (they never interact with Beaker outside of the CLI for creating images, anyway).
This is a counter change to https://github.com/allenai/beaker/pull/125, which I realized would not work well with the leaderboard given the …
> create or use default workspaces if none provided

- cmd/beaker/config/workspace.go
I copied this pattern from the code I added in the Leaderboard, and we discovered today that there's a bug in the error handling logic. If EnsureDefualtWorkspace is called when the workspace doesn't exist, we'd work our way to the CreateWorkspace call, and that call succeeds, but then the function would return at line 58 with values `"", nil`
This change modifies the logic to make sure that we only return in these cases:
1. A non-API error, or an API error that isn't a not found
2. Failure to create the workspace
3. The workspace now exists (either by the initial lookup or a successful create) and we return the reference and no error.
> Fix logic bug in error handling

- cmd/beaker/alpha/tune.go
Tested with the example in this repo. The group and all experiments were correctly created under a workspace https://dev.beaker.org/gr/gr_wy4gqgwjdy5q/compare
> Ensure `tune` passes workspace when creating groups and experiments

- README.md
- cmd/beaker/experiment/run.go
- cmd/beaker/experiment/spec.go
beaker run is still the simplest way to have users on-boarded and using beaker - especially when following https://github.com/allenai/beaker#beaker
I don't think its a good idea to deprecate/remove it, at least to the extent it can be used to run examples from the public `examples` workspace. I have added workspace support and simplified the image bootstrap support.
> Fix beaker experiment run to honor workspaces

- README.md
- cmd/beaker/experiment/run.go
This replaces references to `experiment run` with `experiment create` and adds a deprecation warning.
> Deprecate 'experiment run' command

- cmd/beaker/image/pull.go
- go.mod
Docker's `ImageTag` function returns an error on valid references if they're not in canonical form. For example: 
```bash
beaker image pull examples/wordcount friendly-name
```
The `friendly-name` in this example must be canonicalized to `docker.io/library/friendly-name`.
> Fix tag normalization error on image pull

- cmd/beaker/cluster/create.go
- cmd/beaker/config/test.go
- cmd/beaker/task/cancel.go
- cmd/beaker/task/inspect.go
- go.mod
- go.sum
Example usage:
```
./beaker cluster create --max-size=2 --memory=98GiB --gpu-type=v100 --gpu-count=1 ai2/vivekl-invalid
Cluster ai2/vivekl-invalid created (ID us_5q1tt6xs9mz3/01E4Y5PKS183K0P3Y914E6ZCGK)
Preparing cluster... failed
Error: failed to find candidate machine spec for cluster "ai2/vivekl-invalid":
* n1-highmem: for GPU type 1X v100 max memory is 78 GiB and max CPU count is 12
* n1-highcpu: n1-highcpu: no valid machine exists for the given combination of memory and CPU
* n1-custom: must specify CPU to use a custom instance type
* n1-standard: for GPU type 1X v100 max memory is 78 GiB and max CPU count is 12
```
> Bump beaker client and add cluster failure handling

- config/config.go
For new users, we seem to render experiment links with `defaultAddress` as the base which results in `https://api.beaker.org/ex/ex-blah` which 404s. `api` subdomain is really no longer relevant so removing it.
> Use beaker.org instead of api.beaker.org for default address

- cmd/beaker/experiment/create.go
- cmd/beaker/experiment/run.go
- cmd/beaker/experiment/spec.go
- go.mod
- go.sum
While updating the spec, I noticed some redundancy, so I removed duplicate structs.  We should eventually remove the remainder and use only the `api` package.
> Support direct use of DockerHub images

- cmd/beaker/alpha/tune.go
- cmd/beaker/experiment/create.go
- go.mod
- go.sum
This flag was inconsistently applied and rarely used.  We've opted to remove it to simplify the API, rather than changing its behavior.
> Remove support for experiment create force flag

- go.mod
- go.sum
The new version field is optional in V1 specs, but now appears by default in the UI's rendering, so the CLI needs an update to parse it.
> Update Beaker client to support v1 tag

- cmd/beaker/experiment/create.go
- go.mod
- go.sum
Add CLI support for V2 experiment specs.  I combined this with a small amount of refactor/consolidation in experiment create to make file parsing cleaner.
> Add support for V2 specs

- cmd/beaker/config/workspace.go
- cmd/beaker/dataset/create.go
- cmd/beaker/experiment/create.go
- cmd/beaker/group/create.go
- cmd/beaker/image/create.go
This makes workspace required when creating datasets, experiments, groups, and images.
Workspace can be passed with the `--workspace` flag or set in the configuration file. If the workspace does not exist, it is created. Previously, the workspace was only created automatically if it was not set in the configuration file or passed explicitly.
> Require workspace

- cmd/beaker/experiment.go
- cmd/beaker/group.go
- cmd/beaker/secret.go
Breaking changes:
- `beaker experiment resume --experiment-name <experiment>` changed to `beaker experiment resume <experiment>`
- `beaker experiment create --file <spec file>` changed to `beaker experiment create <spec file>`
- `beaker group create --name <name> <experiment...>` changed to `beaker group create <name> <experiment...>`
- `beaker secret <command> --workspace <workspace>` changed to `beaker secret <command> <workspace>`
> Change all required flags to arguments

- cmd/beaker/execution.go
- cmd/beaker/main.go
- cmd/beaker/task.go
Adds:
- `beaker execution inspect <execution>`
- `beaker execution logs <execution>`
- `beaker task logs <task>`
I decided to keep the log commands simple. They just fetch the entire log and further processing can be done with other tools. Our API doesn't really support anything besides getting the entire log so we're not losing efficiency here.
> Add execution and task log commands

- cmd/beaker/cluster.go
- cmd/beaker/dataset.go
- cmd/beaker/execution.go
- cmd/beaker/experiment.go
- cmd/beaker/group.go
- cmd/beaker/image.go
- cmd/beaker/main.go
- cmd/beaker/node.go
- cmd/beaker/secret.go
- cmd/beaker/task.go
- cmd/beaker/workspace.go
Standardized JSON and table formatting and added commands for managing clusters.
```
$ beaker cluster list ai2 --cloud  
NAME                                GPU TYPE  GPU COUNT  CPU COUNT  MEMORY
ai2/gpu-healthcheck                 p100      1          1          3.75 GiB
ai2/cpu-healthcheck                           0          1          3.75 GiB
ai2/ronan_aclcluster_gpu            v100      4          2          8.00 GiB
ai2/ronan_largemem_cpu                        0          32         208.00 GiB
ai2/aflite_experiments_swabha                 0          32         208.00 GiB
ai2/aristo_extraction               v100      1          8          52.00 GiB
ai2/s2-tldr                         v100      4          32         208.00 GiB
ai2/s2-tldr-8x                      v100      8 …
```
> Add cluster and node commands

- cmd/beaker/main.go
Makes the CLI prompt for a user token if the token is missing or invalid. 
```
You are not logged in. To log in, find your user token here: https://beaker.org/user
Enter your user token: this-is-a-fake-token
Successfully logged in as "lane"
```
> Prompt for login on missing or invalid token

- cmd/beaker/cluster.go
- cmd/beaker/dataset.go
- cmd/beaker/execution.go
- cmd/beaker/experiment.go
- cmd/beaker/group.go
- cmd/beaker/image.go
- cmd/beaker/node.go
- cmd/beaker/organization.go
- cmd/beaker/task.go
- cmd/beaker/workspace.go
Also adds an alias so `beaker <object> inspect` still works.
> Rename inspect commands to get

- README.md
- cmd/beaker/executor_darwin.go
- cmd/beaker/executor_linux.go
- cmd/beaker/main.go
```
beaker executor install -h
```
```
Install the Beaker executor, start it, and configure it to run on boot.
Requires access to /etc, /var, and /usr/bin. Also requires access to systemd.
Usage:
beaker executor install <cluster> [flags]
Flags:
--config-dir string    Writeable directory for Beaker configuration (default "/etc/beaker")
-h, --help                 help for install
--storage-dir string   Writeable directory for storing Beaker datasets (default "/var/beaker")
Global Flags:
--format string   Output format
-q, --quiet           Quiet mode
```
> Add executor installation command

- cmd/beaker/session.go
These mappings interfere with with the shell, with the most obvious being terminal colorization.
> Remove /etc/passwd mounts from default sessions

- cmd/beaker/main.go
Fixes a bug where commands that don't require login, like `beaker config set`, would still prompt for login. This prevents programmatically setting the user token using `beaker config set user_token` in the image builder.
> Don't prompt for login unless necessary

- cmd/beaker/image.go
`NewEnvClient` is deprecated.  The `WithOpts` form replaces it.
> Use docker.NewClientWithOpts

- cmd/beaker/print.go
- cmd/beaker/session.go
```
$ beaker session list --all | head -n 10
ID                          NAME  AUTHOR  STATUS     SCHEDULED        DURATION   GPUS
01F0ESAHJJ2T9P4FN3F0G4WEE1  N/A   lanea   failed     Mar 10 19:20:28  00:00:06   0
01F0ESFMAE5KS4K90WQVCVM5MW  N/A   lanea   failed     Mar 10 19:23:13  00:00:02   0
01F0ESJK23TK596BGF729BFGK2  N/A   lanea   failed     Mar 10 19:24:52  457:27:17  0
01F0ETCJ6B3AB7ZWMAZQ0089QE  N/A   lanea   succeeded  Mar 10 19:45:51  00:01:23   0
01F0ETEWHW837C00EKME37FCWM  N/A   lanea   succeeded  Mar 10 19:47:16  00:01:52   0
01F0ETJ6479N74PNHDHGDV8PP1  N/A   lanea   succeeded  Mar 10 19:49:11  00:01:51   0
01F0EV5Q8MBJE0XPXE0BH3TYYR  N/A   lanea   succeeded  Mar 10 19:52:48  00:01:03   0
01F0EVAGHAQQQ2Z626DMQAC4YA  N/A   lanea   failed     Mar 10 19:55:25  00:00:29   0 …
```
> Make session list command more useful for reporting

- cmd/beaker/main.go
- cmd/beaker/session.go
If the user hits Ctrl-C after before a session is started, we will have an orphaned session. The executor will clean it up eventually, but only after the session is scheduled and not started for 5 minutes. This change automatically cancels the session instead.
> Handle cancellation while starting a session

- go.mod
- go.sum
This updates to the latest Beaker runtime release, which fixes
a bug where all of the GPUs on a host were exposed to
interactive sessions that don't request GPUs.
> Update Beaker runtime.

- cmd/beaker/experiment.go
- cmd/beaker/session.go
During session creation, instead of waiting forever with an ever-expanding ellipsis, Beaker will now detect whether the session is likely to schedule.  If not, it prints a message indicating why the session is waiting and redirects the user to other nodes.
> Make session feedback more immediate

- cmd/beaker/cluster.go
- cmd/beaker/session.go
This also makes the flags `cpus` and `gpus` standard and deprecates `cpu-count` and `gpu-count`.
> Support CPU and memory reservations in sessions

- cmd/beaker/session.go
Prior to this change we were using the original image tag,
as passed by the client. This will look something like:
```
beaker://sams:latest
```
The "scheme" is something that's specific to our client which
won't be understood by Docker, so we need to use the resolved
image instead.
> Use the resolved image.

- cmd/beaker/session.go
It turns out the `Name` property of `User` can be blank.
From https://golang.org/pkg/os/user/#User:
```
// Username is the login name.
Username string
// Name is the user's real or display name.
// It might be blank.
// On POSIX systems, this is the first (or only) entry in the GECOS field
// list.
// On Windows, this is the user's display name.
// On Plan 9, this is the contents of /dev/user.
Name string
```
It appears this is often the case, as it's what caused the bug
Oyvind and MattG ran into. They both ended up getting a home
path of `/var/beaker/home`, because `u.Name` was `""`.
This fixes that by using `Username`. I built a binary and
tested this out on `beaker-server1` (where I can't technically launch
a session, but I used good ole' `PrintLn()` debugging to make sure
the path was …
> Create separate alt-home dirs for each user.

- cmd/beaker/executor.go
- cmd/beaker/session.go
Part 2 of 3 for NFS-based roaming profiles: coordinate with the installed executor when possible to determine the session home directory mount.
> Enable configurable home directory

- cmd/beaker/session.go
This replaces an often confusing error about an invalid image with a clearer error prompting the user to sign in.
> Produce a more useful error when user hasn't authed

- cmd/beaker/main.go
- cmd/beaker/session.go
We had a special case for this but it only handled a missing token, not an incorrect one. I made the general error handling for invalid tokens handle wrapped errors so this special case is no longer necessary. 
Fixes https://github.com/allenai/beaker/issues/304
> Prompt for token if not logged in when creating a session

- cmd/beaker/executor.go
- cmd/beaker/session.go
Currently, if `sessionHome` is not configured, `~/<user>` is used e.g. `/home/lanea/lanea`. ​I think this is a bug that we didn't notice because we always configure `sessionHome`. This change makes `sessionHome` default to `~`.
Part of https://github.com/allenai/reviz/issues/263
> Fix default session home

- cmd/beaker/session.go
Fixes https://github.com/allenai/beaker-service/issues/1504
In `checkNodeCapacity`, we were checking the session's request against the node's limits. If the session's request was empty, as it usually is, the capacity check would always pass, even if the node had no resources left.
Since the session's limits are not populated until the session is scheduled, we can't check against that. Instead, I added a check for zero node resources. If the node has no resources left, the session won't be able to schedule, no matter its request. We will print the following error instead of hanging:
```
This session is unlikely to to start because the node has no space left.
You may continue waiting to hold your place in the queue.
```
I also added back the `Waiting for session to be scheduled...` message. …
> Fix hang on verifying image

- cmd/beaker/print.go
This was failing because `cluster.NodeShape.Memory` is `nil` in
some cases. After this change the CLI will print `N/A` instead
of segfaulting.
I tried to find a recent change that may have caused this but
couldn't. That said being defensive here doesn't seem like
a bad thing to do, so I don't feel the need to exhaustively
root cause this.
> Fix #1565; Don't panic when cluster nodes dont have memory.

- cmd/beaker/cluster.go
- cmd/beaker/print.go
- cmd/beaker/workspace.go
This change addresses some usability issues I noticed while updating docs.
```diff
▶ beaker workspace create foo
- Workspace foo created (ID 01FBK09NXR60M06BGC3JVKBNRY)
+ Workspace ckarenz/foo created. See details at https://beaker.org/ws/ckarenz/foo
```
```diff
▶ beaker cluster create ai2/foo
- Cluster ai2/foo created (ID us_wvnghctl47k0/01FBK08HSBZ933WVJB3YDSMHTT)
+ Cluster ai2/foo created. See details at https://beaker.org/cl/ai2/foo
```
```diff
▶ beaker image get examples/wordcount
- ID         WORKSPACE  AUTHOR    CREATED
- wordcount  examples   examples  Aug 22 22:47:10
+ ID                  WORKSPACE          AUTHOR    CREATED
+ examples/wordcount  examples/examples  examples  2018-08-22 15:47:10
```
```diff
▶ beaker dataset get examples/moby
- ID    WORKSPACE  AUTHOR    COMMITTED …
```
> Fix inconsistent name/ID treatment

- cmd/beaker/session.go
Fixes https://github.com/allenai/beaker-service/issues/1605
When checking for capacity, we were subtracting the limits of every job on the cluster from the current node. This caused a false capacity error.
> Fix incorrect capacity error when creating sessions

- cmd/beaker/image.go
This addresses a common issue where the host machine is slightly behind the CLI's docker dependency.
> Negotiate Docker API version

- cmd/beaker/session.go
- go.mod
- go.sum
Part of https://github.com/allenai/beaker-service/issues/1546
Adds:
- `--save-image`/`-s` flag to `beaker session create`. If provided, the executor will commit the image once the session exits and push it to a new image in the session's workspace.
- `beaker session images` command which gets the result images of a session.
Here's what saving an image looks like:
```
$ beaker session create --save-image
Starting session 01FF5SGZX5HA9SQYWXMYPK322A... (Press Ctrl+C to cancel)
Waiting for session to start. Done!
WARNING: The root filesystem of this session will be saved.
Do not write sensitive information outside of the home directory.
/Users/lanea $ ...
Waiting for image capture to complete... Done!
Image saved to 01FF5SHGSPS678XGBXBFZ61T3Z: https://beaker.org/im/01FF5SHGSPS678XGBXBFZ61T3Z …
```
> Add support for saving session images

- cmd/beaker/executor_linux.go
Before, the `beaker executor install` command would implicitly write executor config. This caused a problem when https://github.com/allenai/beaker-service/pull/1759 was merged because the executor had no way to set `resources.gpus: []` for CPU-only machines.
Instead of adding another configuration flag to `beaker executor install` I decided to split out configuration into `beaker executor configure`. This supports very limited configuration for simple installations:
```
beaker executor configure <cluster>
beaker executor install
```
More complicated installations can write a custom configuration file:
```
cat << EOF > /etc/beaker/config.yml
storagePath: /var/beaker
logLevel: debug
beaker:
address: https://beaker.org
tokenPath: /etc/beaker/token
cluster: ai2/cluster
resources:
gpus: []
EOF …
```
> Split executor configuration and installation

- cmd/beaker/config.go
- cmd/beaker/main.go
- config/config.go
- go.mod
- go.sum
Fixes https://github.com/allenai/beaker-service/issues/1728
If a user doesn't have a default workspace configured, they will get a nice prompt like this:
```
No default workspace is configured. Please select one of your workspaces:
0. ai2/lane-test-workspace (0 experiments)
1. ai2/lane (30 experiments)
2. ai2/lanea (72 experiments)
Enter a number from the list above or the name workspace e.g. ai2/my-workspace.
The workspace will be created if it does not exist yet.
Default workspace: 1
Setting default workspace to ai2/lane
```
If they don't have any workspaces yet it looks like this:
```
No default workspace is configured. You have no existing workspaces.
Enter the name of a new workspace e.g. ai2/my-workspace.
The workspace will be created if it does not exist yet.
Default workspace: …
```
> Make it easy to configure a default workspace

- cmd/beaker/config.go
- cmd/beaker/session.go
- config/config.go
Fixes https://github.com/allenai/beaker-service/issues/1841
Adds the `default_image` property to Beaker config. This is updated by `beaker session create --save-image` unless the `--update-default-image=false` flag is set.
Start a session from `busybox` and save the result:
```
$ beaker session create -i docker://busybox --save-image
Defaulting to workspace ai2/lanea
Starting session 01FST9VEETKR5Y20WJ2ZR7RJEA... (Press Ctrl+C to cancel)
Waiting for session to start...... Done!
WARNING: The root filesystem of this session will be saved.
Do not write sensitive information outside of the home directory.
/Users/lanea $ ...
Waiting for image capture to complete........ Done!
Image saved to 01FST9VSEC3DC9JES5TSMECKG2: https://dev.beaker.org/im/01FST9VSEC3DC9JES5TSMECKG2
Default image updated. …
```
> Add default session image to config

- cmd/beaker/job.go
- cmd/beaker/main.go
- config/config.go
I've added an HTTP diagnostics setting (env var BEAKER_HTTP_DIAG set to `true`, or config setting http_diag set to true).
Using it, I see that before this change, listing listing jobs on a specific node did not include the node in the request:
```
$ BEAKER_HTTP_DIAG=true BEAKER_CONFIG_FILE=/Users/michalg/.beaker/config-dev.yml ./beaker job list --node 01FST4XHNQR5H9DFJ38VB55MVQ
Beaker HTTP diagnostic: status_code = 200 duration_ms = 411 request = GET https://dev.beaker.org/api/v3/jobs?finalized=false
ID                          KIND       NAME          AUTHOR       STATUS   SCHEDULED  DURATION  GPUS  NODE
01EG6CHV4QT04VM6F98Z3VG06T  execution  echo          ckarenz      pending  N/A        00:00:00  N/A   N/A
01EQM8TCSER8AYCS6W343CQXQQ  execution  nvidia-smi    michaels     pending  N/A …
```
> fix job list 

- cmd/beaker/session.go
re: https://github.com/allenai/beaker-service/issues/1813
Cleaning up since this option is no longer needed as it happens by default.
> remove local home option

- cmd/beaker/executor.go
- cmd/beaker/executor_linux.go
I tried walking through the self hosting instructions, but ran into a bug. The
executor wouldn't start because of an error at at startup:
```
error: getting storage path: $HOME is not defined
```
That error originates from [this code](https://github.com/allenai/beaker-service/blob/5a9afb877321519943eb2f2d1446b9f4c367c1a8/cmd/executor/main.go#L122-L125),
which is executed as the executor starts up.
The error occurs because we try to use the process owner's [home directory](https://github.com/allenai/beaker-service/blob/5a9afb877321519943eb2f2d1446b9f4c367c1a8/cmd/executor/main.go#L48)
as a default, but because the process is ran non-interactively, `$HOME` isn't set.
This fixes that by explicitly setting the storage path to `/var/beaker`, and
by making sure that directory exists. …
> Fix the configure command.

- cmd/beaker/session.go
- go.mod
- go.sum
This adds the `--port` flag to the `beaker session create`
command.
This codebase doesn't have any tests. So I tested manually.  I started
a local executor, then build a local `beaker` CLI and started a session
like so:
```
❯ ./beaker session create \
--node 01G16Y53QY0YYNYPDNRYJ1A36T \
--image beaker://sams/cuda11.2-ubuntu20.04 \
--port 8888
```
This worked! The `docker ps` command shows the container, with a random port
bound to container port `8888`:
```
❯ docker ps
CONTAINER ID   IMAGE                                                     COMMAND     CREATED          STATUS          PORTS                     NAMES
0a63319a448d   gcr.io/ai2-beaker-core/uploads/dev/c7g9tvj56ghj02m8t4g0   "bash -l"   27 seconds ago   Up 25 seconds   0.0.0.0:55106->8888/tcp …
```
> Add flag for exposing session ports.

- cmd/beaker/session.go
- go.mod
- go.sum
This adds code for printing the exposed ports when the container
starts.
It looks like so:
```
❯ ./beaker session create --port 8888 --port 8889
Defaulting to workspace org/name
Starting session ZZZ... (Press Ctrl+C to cancel)
Waiting for session to start.. Done!
Exposed Ports: 0.0.0.0:55117->8888/tcp, 0.0.0.0:55116->8889/tcp
[beaker] sams ~ $
```
I'll add this to other commands, like `beaker session get` too in
the near future.
> Print exposed ports on session start.

- cmd/beaker/print.go
- cmd/beaker/session.go
This PR adds the `beaker session describe` command, which
prints detailed information about a running session.
As part of this I decided to delete the `inspect` alias for
`beaker session get`. I figured it's probably not used, and
confusing if `inspect` doesn't do what `describe` does now.
The describe output looks like so as text:
```
❯ ./beaker session describe ZZZ
ID         ZZZ
Name       N/A
User       Sam "Skjonsie" Skjons🍔 (sams)
Image      beaker://sams/cuda11.2-ubuntu20.04
https://dev.beaker.org/im/YYY
Started    2022-04-22 14:35:57
Elapsed    00:16:14
Status     running
GPUS       N/A
TCP Ports  sams.macbook:55125->8888/tcp (http://sams.macbook:55125)
sams.macbook:55124->8889/tcp (http://sams.macbook:55124)
```
...and like so as JSON:
```
❯ ./beaker session describe ZZZ --format …
```
> Add command for showing detailed session information.
