api/task.go

ExperimentID needs to be exposed here before testing change in beaker-service

adding ExperimentID to Task struct

---

api/searchfield/group_tasks.go

See https://github.com/allenai/beaker-service/pull/283

Add status as a group search field

---

client/client.go

I want to make a new CLI release which includes my previous work on statuses. This change bumps up the version constant to today's date. Please let me know if there's anything else I need to change before merging (& I guess it also needs to make it to master to be released?)

Rev client version in preparation for release

---

api/searchfield/group_tasks.go

Rev client version in master

---

Gopkg.toml
client/blueprint.go
client/client.go
client/dataset.go
client/experiment.go
client/file.go

Adds retry to client requests except for file upload and download. Since these are long-lived requests, retries will be handled differently.

Retry in client

---

api/cost.go
api/machine.go
api/organization.go
api/reports.go
api/task.go
api/user.go
go.mod
go.sum

These are the remaining differences between the /api folder in beaker-service and this repo's /api folder.

Sync beaker API files with beaker-service repo

---

api/dataset.go
client/dataset.go
go.mod
go.sum

Deferring `go mod tidy` until we get everything up to 1.11.4.

Add FileHeap tokens to client

---

README.md
api/task.go
cmd/beaker/experiment/run.go
cmd/beaker/experiment/run_test.go
cmd/beaker/experiment/spec.go
cmd/beaker/experiment/spec_test.go
cmd/beaker/options/options.go

Removing options.MakeRequirements since not used.

Add GPUType parameter

---

api/searchfield/dataset.go
api/searchfield/experiment.go
api/searchfield/group.go
go.sum

I'm adding owner to the search data tables, and need to this to be able to sort by owner!

Add owner as searchfield for dataset, group, and experiment

---

client/experiment.go

This lets me search experiments using the client.

SearchExperiments

---

cmd/beaker/dataset/create.go

Disable creating legacy datasets

---

client/organization.go

Error context mangled organization errors, making the text confusing to CLI users.

Clarify org error string

---

api/reports.go
api/user.go

The complementary API struct changes for my recent commit in beaker-service (https://github.com/allenai/beaker-service/commit/f8d4a0d0a5e073f530f8ca80bd1c6a6c5dd2ba52)

Add ReportGroup field to User and Report structs

---

cmd/beaker/cluster/create.go

- Fix GPU always displaying "none"
- Round node cost

Fix summary display on cluster creation

---

cmd/beaker/dataset/fetch.go
go.mod
go.sum

Show progress as a percentage when dataset size is known.
Old:
```
Downloading ds_mz41m5xdjkwq to test1/
Files: 3          1 in progress ⠇  
Bytes: 7.54MiB    44.86MiB in progress ⠇  
```
New:
```
Downloading ds_mz41m5xdjkwq to test1/
Files: 3          /          4 [===================================>------------]  75% 1 in progress ⠋
Bytes: 7.54MiB    /    52.4MiB [======>-----------------------------------------]  14% 44.86MiB in progress ⠋
```

Show progress as a percentage on dataset fetch

---

cmd/beaker/cluster/create.go
cmd/beaker/cluster/inspect.go
cmd/beaker/cluster/terminate.go
cmd/beaker/cluster/update.go

Clusters are vetted and required.

Remove experimental warnings from cluster commands

---

cmd/beaker/config/set.go
go.mod
go.sum

Also bump beaker client version.
Fixes: #162

Fix handling of non-existent config

---

cmd/beaker/dataset/root.go
cmd/beaker/experiment/delete.go
cmd/beaker/experiment/root.go
cmd/beaker/image/root.go
cmd/beaker/task/root.go
go.mod
go.sum

This helps bring the UI and CLI closer to parity in capabilities.

Add 'experiment delete' command to CLI

---

cmd/beaker/image/delete.go
cmd/beaker/image/root.go
go.mod
go.sum

This follows the `dataset delete` command verbatim.

Add command to delete images

---

go.mod
go.sum

This propagates a few spec changes from the API.

Update Beaker API client

---

.circleci/config.yml

Copied this from the Makefile, syntax doesn't quite work in bash.

Fix release CCI step

---

cmd/beaker/print.go

Show correct value for execution status

---

cmd/beaker/session.go
go.mod
go.sum

The CLI now creates sessions instead of the executor.

Create sessions in the CLI

---

cmd/beaker/session.go
go.mod
go.sum

Waiting on a change to the runtime to merge.

Add session exec command

---

cmd/beaker/dataset.go

- Change the default output path of `dataset fetch` from "" to "."
- Add support for `--prefix` in `dataset fetch`

Fix dataset fetch

---

cmd/beaker/cluster.go

Fixes https://github.com/allenai/beaker-service/issues/1383
Provides a list of valid GPU types and counts. Validation is left up to the provisioner so this may become outdated.

Clarify which GPU types are available

---

go.mod
go.sum

This fixes a panic when printing nil byte quantities.

Update bytefmt dependency

---

cmd/beaker/session.go

Replace 'session update --cancel' with 'session stop'

---

cmd/beaker/session.go

This presumes there exists a `/var/beaker/home` directory with appropriate permissions in which all users can create subdirectories.  It shouldn't merge until the corresponding agent code is updated.

Add experimental flag for alternate home mount

---

config/config.go

This change updates environment variables used for configuration to match patterns in other AI2 tools.
- Environment variables now take precedence over file config.
- Override config path: rename `BEAKER_CONFIG_FILE` -> `BEAKER_CONFIG`. The old key still works temporarily.
- Add option to override the user authentication token through `BEAKER_TOKEN`.

Update config environment variables

---

cmd/beaker/session.go

Now that the Beaker Image Fabricator is in working order:
github.com/allenai/beaker-images

Update the default interactive image.

---

cmd/beaker/session.go
go.mod
go.sum

Fixes https://github.com/allenai/beaker-service/issues/1502.
Depends on https://github.com/allenai/beaker-service/pull/1506.

Fix output of commands in Beaker interactive

---

cmd/beaker/dataset.go
cmd/beaker/experiment.go
cmd/beaker/group.go
cmd/beaker/image.go
cmd/beaker/print.go
cmd/beaker/workspace.go
go.mod
go.sum

This updates Beaker CLI to use new Patch operations.

change set* calls to Patch calls

---

cmd/beaker/session.go
go.mod
go.sum

Part of https://github.com/allenai/beaker-service/issues/1557
Depends on https://github.com/allenai/beaker-service/pull/1629

Add support for shared memory in sessions

---

cmd/beaker/main.go
cmd/beaker/session.go
go.mod
go.sum

Part of https://github.com/allenai/beaker-service/issues/1592

Support secrets in sessions

---

cmd/beaker/job.go

Add `beaker job finalize` which is useful for clearing out jobs that are stuck in finalization.

Add job finalize command

---

cmd/beaker/dataset.go

Adds `beaker dataset sync` command:
```
beaker dataset create --commit=false <source>
beaker dataset sync <source> <dataset>
beaker dataset commit <dataset>
```

Add dataset sync command

---

cmd/beaker/secret.go

The secret commands require a workspace argument instead of using the default workspace and accepting a `--workspace` flag. This change makes the secret commands consistent with other commands. 
Part of https://github.com/allenai/beaker-service/issues/1728

Make secret commands accept workspace flag
